# Generated by Django 3.1 on 2020-08-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('scard', models.CharField(max_length=100)),
                ('sroom', models.CharField(max_length=100)),
            ],
        ),
    ]
