# Generated by Django 3.1 on 2020-09-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ID', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scampus',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
